clusterName:
poolName:
# Defaults to KarpenterNodeRole-{{ .Values.clusterName }}
# nodeRoleName:
cpuLimit: 8
memoryLimit: 64Gi
consolidationPolicy: WhenEmptyOrUnderutilized
consolidateAfter: 20s
# AMI Configuration
amiSelectorTerms:
  - alias: "bottlerocket@latest"

# Instance Configuration
#instanceType: 
#  - "m5.large"
instanceCpu: 
  - "2"
  - "4"

instanceFamily: 
  - "m5"
  - "c5"
  - "r5"
  - "m5a"
  - "c5a"
  - "r5a"
  - "m6"
  - "c6"
  - "r6"
  - "m6a"
  - "c6a"
  - "r6a"  

capacityType: 
  - "spot"
  - "on-demand"
