apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: lake-worker
  labels:
    "ingext.io/app": "lake-worker"
spec:
  replicas: 1
  selector:
    matchLabels:
      "ingext.io/app": "lake-worker"

  ## Pod configuration template.
  template:
    metadata:
      annotations:
        {{- if eq .Values.k8sProvider "gcp" }}
        "gke-gcsfuse/volumes": "true"
        "gke-gcsfuse/ephemeral-storage-request": "2Gi"
        {{- end }}    
      labels:
        "ingext.io/app": "lake-worker"
        {{- if eq .Values.k8sProvider "azure" }}
        "azure.workload.identity/use": "true"
        {{- end }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ .Release.Namespace }}-sa
      ##
      ## Containers in the pod
      volumes:
        - name: lake-config-volume
          configMap:
            name: ingext-lake-config
        - name: config-volume
          configMap:
            name: ingext-community-config
        - name: lake-volume
          persistentVolumeClaim:
            claimName: cloud-storage-{{ .Release.Namespace }}
        - name: "tmpfs-data"
          emptyDir: 
            medium: Memory
            sizeLimit: 100Mi                    
      containers:
      ## This example only has this etcd container.
      - name: lake-worker
        image: public.ecr.aws/ingext/ingext_lake_worker:{{ .Values.lakeWorkerVersion }}
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "0.2"
            memory: 600Mi
          limits:
            cpu: "0.3"
            memory: 800Mi
        env:
          - name: K8S_PROVIDER
            value: {{ .Values.k8sProvider }}
          - name: POD_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: ETCDCTL_API
            value: "3"
          - name:  ETCDCTL_ENDPOINTS
            value: "http://etcd:2379"    
        ##
        ## This is the mount configuration.
        volumeMounts:
          - name: config-volume
            mountPath: "/etc/config"
          - name: lake-volume
            mountPath: /lake            
          - name: "tmpfs-data"
            mountPath: /data  
          - name: lake-config-volume
            mountPath: "/etc/lake/config"
