apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: {{ .Values.poolName }}
spec:
  limits:
    cpu: "{{ .Values.cpuLimit }}"
    memory: "{{ .Values.memoryLimit }}"
  template:
    metadata:
      labels:
        node-pool: {{ .Values.poolName }}
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: {{ .Values.poolName }}
      requirements:
        - key: "karpenter.k8s.aws/instance-cpu"
          operator: In
          values: {{ .Values.instanceCpu | toJson }}
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: {{ .Values.capacityType | toJson }}
        - key: "karpenter.k8s.aws/instance-family"
          operator: In
          values: {{ .Values.instanceFamily | toJson }}
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]  
      taints:
        - key: node-pool
          value: {{ .Values.poolName }}
          effect: NoSchedule
  disruption:
    consolidationPolicy: {{ .Values.consolidationPolicy }}
    consolidateAfter: {{ .Values.consolidateAfter }}
