lakeMgrVersion: latest
searchServiceVersion: latest
lakeWorkerVersion: latest
lakeSearchVersion: latest

podLabels: {}
# azure.workload.identity/use: "true"
# Options: eks, aks, gke
k8sProvider: "aws"