lakeMgrVersion: "1.1.0"
searchServiceVersion: "1.1.0"
lakeWorkerVersion: "1.1.0"
lakeSearchVersion: "1.1.0"

podLabels: {}
# azure.workload.identity/use: "true"
# Options: eks, aks, gke
k8sProvider: "aws"