{{- if .Values.ingress.createBackendConfig }}
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: api-backend-config
  namespace: {{ .Release.Namespace }}
spec:
  timeoutSec: 300  
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 3
    type: HTTP
    port: 8002
    requestPath: /health-check
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: platform-backend-config
  namespace: {{ .Release.Namespace }}
spec:
  timeoutSec: 300
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 3
    type: HTTP
    port: 28180
    requestPath: /health-check
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: fluency-backend-config
  namespace: {{ .Release.Namespace }}
spec:
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 3
    type: HTTP
    port: 8004
    requestPath: /health-check
{{- end }}

