apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Namespace }}-sa
  namespace: {{ .Release.Namespace }}
  annotations:
    # 1. AWS IRSA Annotation
    {{- if .Values.serviceAccount.awsRoleArn }}
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.awsRoleArn | quote }}
    {{- end }}

    # 2. Azure Workload Identity Annotation
    {{- if .Values.serviceAccount.azureClientId }}
    azure.workload.identity/client-id: {{ .Values.serviceAccount.azureClientId | quote }}
    {{- end }}

    # 3. Allow custom annotations from values.yaml (optional but good practice)
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: true
