apiVersion: v2
name: ingext-stack
description: A wrapper chart for Redis, OpenSearch, and VictoriaMetrics
type: application
version: 1.1.0
appVersion: "1.0.0"

dependencies:    
  - name: victoria-metrics-single
    version: 0.26.0
    repository: https://victoriametrics.github.io/helm-charts/
