---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-lake
spec:
  capacity:
    storage: {{ .Values.storage }} # Ignored, required
  accessModes:
    - ReadWriteMany # Supported options: ReadWriteMany / ReadOnlyMany
  storageClassName: "" # Required for static provisioning
  claimRef: # To ensure no other PVCs can claim this PV
    namespace: {{ .Release.Namespace }} # Namespace is required even though it's in "default" namespace.
    name: cloud-storage-{{ .Release.Namespace }}
  mountOptions:
    - allow-delete
    - region {{ .Values.bucket.region }}
  csi:
    driver: s3.csi.aws.com # Required
    volumeHandle: s3-csi-driver-{{ .Release.Namespace }}-lake # Unique identifier for the volume
    volumeAttributes:
      bucketName: {{ .Values.bucket.name }}
      authenticationSource: "pod"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloud-storage-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes: {{- .Values.accessModes | toYaml | nindent 4 }}
  storageClassName: "" # Required for static provisioning
  resources:
    requests:
      storage: {{ .Values.storage }} # Ignored, required
  volumeName: s3-lake # Name of your PV