apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClassName | default "ingext-aws-gp3" }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "{{ .Values.isDefault | default "true" }}"
provisioner: ebs.csi.aws.com # The correct provisioner for the Amazon EBS CSI driver
parameters:
  type: gp3
  encrypted: "{{ .Values.encrypted | default "true" }}" # Optional, but recommended for security
reclaimPolicy: {{ .Values.reclaimPolicy | default "Delete" }}
volumeBindingMode: {{ .Values.volumeBindingMode | default "WaitForFirstConsumer" }}
allowVolumeExpansion: {{ .Values.allowVolumeExpansion | default true }}
