apiVersion: v1
kind: ConfigMap
metadata:
  name: ingext-lake-config
  namespace: {{ .Release.Namespace }}
data:
  lake_storage_config.json: |
    {
      "storageType": "{{ .Values.storageType }}",
      "s3": {
        "bucket": "{{ .Values.s3.bucket }}",
        "region": "{{ .Values.s3.region }}"
      },
      "blob": {
        "storageAccount": "{{ .Values.blob.storageAccount }}"
      },
      "gcs": {
        "bucket": "{{ .Values.gcs.bucket }}"
      }
    }
