apiVersion: v1
kind: Service
metadata:
  name: datalake-api
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  ports:
    - port: 19010
      targetPort: 19010
      name: datalake-api
  selector:
    "ingext.io/app": "lake-mgr"
