apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluency7
  namespace: {{ .Release.Namespace }}
  labels:
    "ingext.io/app": "fluency7"
spec:
  replicas: 1
  selector:
    matchLabels:
      "ingext.io/app": "fluency7"
  template:
    metadata:
      labels:
        "ingext.io/app": "fluency7"
    spec:
      # serviceAccountName: {{ .Release.Namespace }}-sa
      containers:
        - name: fluency7
          image: "public.ecr.aws/ingext/fluency7:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8004
              protocol: TCP
          livenessProbe:
            httpGet:
              path: "/health-check"
              port: 8004
            initialDelaySeconds: 3
            periodSeconds: 3
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
            
