apiVersion: v1
kind: Service
metadata:
  name: api-local
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  ports:
    - port: 28080
      targetPort: 28080
      name: api-local
  selector:
    "ingext.io/app": "api"
