apiVersion: v1
kind: Service
metadata:
  name: platform-service
  namespace: {{ .Release.Namespace }}
  annotations:
    cloud.google.com/backend-config: '{"default": "platform-backend-config"}'
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  ports:
    - port: 28180
      targetPort: 28180
      name: platform
  selector:
    "ingext.io/app": "platform"
