apiVersion: v1
kind: Service
metadata:
  name: fluency8
  namespace: {{ .Release.Namespace }}
  annotations:
    cloud.google.com/backend-config: '{"default": "fluency-backend-config"}'
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  ports:
    - port: 8004
      targetPort: 8004
      name: ui
  selector:
    "ingext.io/app": "fluency8"
