apiVersion: v1
kind: Service
metadata:
  name: search-service
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 19100
      targetPort: 19100
      name: search-service
  selector:
    "ingext.io/app": "search-service"
